#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export ROOT_DIR
echo "[content-verify] checking json payloads and basic dictionary rules"
python3 - <<'PY2'
import json, pathlib, os, sys
root = pathlib.Path(os.environ["ROOT_DIR"])
files = [
    root / "data/reference/reference-data.json",
    root / "data/reference/reference-data.extended.json",
    root / "data/reference/reference-data.citymap.v1.json",
    root / "data/reference/reference-data.v7.routing.json",
    root / "data/ui/ui-texts.pl-PL.json",
    root / "data/ui/role_hud_panels.v3.json",
    root / "data/balance/spawn_weights.json",
    root / "data/art/icon_catalog.json",
    root / "data/art/sprite_atlas_manifest.json",
    root / "data/art/route_overlay_prompt_pack.json",
    root / "data/content/vertical-slice.quickplay.json",
    root / "data/content/incident-type-catalog.v2.json",
    root / "data/content/dispatch-unit-roster.json",
    root / "data/content/status-effects.json",
    root / "data/content/city-map.v1.json",
    root / "data/content/unit-roster.live.v1.json",
    root / "data/content/incident-actions.v1.json",
    root / "data/content/report-timeline-demo.v1.json",
    root / "data/content/active-incidents.v1.json",
    root / "data/content/map-filters.v1.json",
    root / "data/content/shared-actions.v1.json",
    root / "data/content/route-preview-demo.v1.json",
    root / "data/content/role-bot-profiles.v2.json",
    root / "data/audio/role_audio_priorities.json",
    root / "data/audio/shared_action_audio.json",
    root / "data/reference/reference-data.v8.rounds.json",
    root / "data/ui/splitscreen_panels.v1.json",
    root / "data/content/route-overlay.v1.json",
    root / "data/content/live-incident-deltas.v1.json",
    root / "data/content/coop-round-loop.v1.json",
    root / "data/content/unit-cooldowns.v1.json",
    root / "data/audio/round_tension_states.json",
    root / "data/art/route_heatmap_prompt_pack.json",
    root / "data/content/menu-flow.v1.json",
    root / "data/content/meta-progression.v1.json",
    root / "data/content/scene-variants.v1.json",
    root / "data/art/menu_scene_prompt_pack.json",
    root / "data/art/object_library_prompt_pack.json",
    root / "data/art/parallax_layers.v1.json",
    root / "data/audio/menu_music_states.v1.json",
    root / "data/audio/sfx_pack_menu_radio_city.v1.json",
    root / "data/audio/music_cue_sheet.v1.json",
    root / "data/ui/menu_widgets.v1.json",
    root / "data/reference/reference-data.v9.menuartaudio.json",
    root / "data/content/home-hub.v1.json",
    root / "data/content/campaign-overview.v1.json",
    root / "data/content/daily-challenges.v1.json",
    root / "data/content/settings-bundle.v1.json",
    root / "data/art/main_menu_renderer_layers.v1.json",
    root / "data/art/expanded_object_library.v1.json",
    root / "data/ui/home_cards.v1.json",
    root / "data/audio/screen_audio_routing.v1.json",
    root / "data/audio/lobby_music_pack.v1.json",
    root / "data/audio/voice_barks_radio_calls.v1.json",
    root / "data/reference/reference-data.v10.homeflow.json",
    root / "data/content/campaign-chapters.v1.json",
    root / "data/content/mission-entry-flow.v1.json",
    root / "data/content/profile-cosmetics.v1.json",
    root / "data/content/portrait-packs.v1.json",
    root / "data/content/animated-menu-weather.v1.json",
    root / "data/content/chapter-map-nodes.v1.json",
    root / "data/audio/home_to_round_audio.v1.json",
    root / "data/audio/campaign_map_music_layers.v1.json",
    root / "data/ui/chapter_map_panels.v1.json",
    root / "data/art/chapter_map_prompt_pack.json",
    root / "data/reference/reference-data.v11.campaignentry.json",
    root / "data/content/chapter-runtime.v1.json",
    root / "data/content/role-selection-botfill.v1.json",
    root / "data/content/round-bootstrap.v1.json",
    root / "data/content/objectives-grading.v1.json",
    root / "data/content/final-vertical-slice-scenes.v1.json",
    root / "data/art/final_vertical_slice_prompt_pack.json",
    root / "data/art/role_card_prompt_pack.json",
    root / "data/audio/round_bootstrap_audio.v1.json",
    root / "data/audio/final_vertical_slice_music.v1.json",
    root / "data/audio/city_radio_dialogues.v1.json",
    root / "data/ui/role_selection_panels.v1.json",
    root / "data/reference/reference-data.v12.runtimebootstrap.json",
    root / "data/content/mission-briefing.v1.json",
    root / "data/content/team-readiness.v1.json",
    root / "data/content/postround-report.v1.json",
    root / "data/content/reward-track.v1.json",
    root / "data/content/mission-complete-flow.v1.json",
    root / "data/art/briefing_prompt_pack.json",
    root / "data/art/role_cards_team_prompt_pack.v2.json",
    root / "data/audio/mission_briefing_audio.v1.json",
    root / "data/audio/postround_report_audio.v1.json",
    root / "data/audio/dialogue_pack_v3.json",
    root / "data/ui/mission_briefing_panels.v1.json",
    root / "data/ui/postround_report_panels.v1.json",
    root / "data/reference/reference-data.v13.briefingreport.json",
    root / "data/content/full-mission-runtime.v1.json",
    root / "data/content/mission-complete-gate.v1.json",
    root / "data/content/runtime-dispatch-outcomes.v1.json",
    root / "data/content/objective-tracker.v1.json",
    root / "data/content/mission-script.01.full.json",
    root / "data/art/full_mission_runtime_prompt_pack.json",
    root / "data/audio/full_mission_runtime_audio.v1.json",
    root / "data/audio/dispatch_outcome_audio.v1.json",
    root / "data/ui/full_mission_runtime_panels.v1.json",
    root / "data/reference/reference-data.v14.fullmission.json",
    root / "data/content/playable-runtime-map.v1.json",
    root / "data/content/objective-state-machine.v1.json",
    root / "data/content/dispatcher-loop.v1.json",
    root / "data/content/city-pressure-runtime.v1.json",
    root / "data/content/report-progression.v1.json",
    root / "data/art/playable_runtime_map_prompt_pack.json",
    root / "data/art/reward_report_room_prompt_pack.json",
    root / "data/audio/playable_runtime_music.v1.json",
    root / "data/audio/runtime_unit_voice_sfx.v1.json",
    root / "data/ui/playable_runtime_panels.v1.json",
    root / "data/reference/reference-data.v15.playableflow.json",
    root / "data/content/live-route-runtime.v1.json",
    root / "data/content/round-timer.v1.json",
    root / "data/content/chain-escalation-runtime.v1.json",
    root / "data/content/demo-mission-polish.v1.json",
    root / "data/art/live_route_renderer_prompt_pack.json",
    root / "data/art/demo_mission_polish_prompt_pack.json",
    root / "data/audio/live_route_timer_chain_audio.v1.json",
    root / "data/audio/demo_mission_polish_music.v1.json",
    root / "data/ui/live_route_timer_panels.v1.json",
    root / "data/reference/reference-data.v16.liveroute.json",
    root / "data/content/visual-runtime-route-layer.v1.json",
    root / "data/content/recovery-decision-cards.v1.json",
    root / "data/content/mission-fail-branches.v1.json",
    root / "data/content/report-room-polish.v1.json",
    root / "data/content/quasi-production-demo-flow.v1.json",
    root / "data/art/runtime_route_layer_prompt_pack.v2.json",
    root / "data/art/failstate_reportroom_prompt_pack.json",
    root / "data/audio/recovery_fail_report_audio.v1.json",
    root / "data/audio/quasi_production_demo_music.v1.json",
    root / "data/ui/recovery_fail_report_panels.v1.json",
    root / "data/reference/reference-data.v17.quasiprod.json",
    root / "data/content/release-candidate-package.v1.json",
    root / "data/content/bug-bash-checklist.v1.json",
    root / "data/content/release-notes-draft.v1.json",
    root / "data/content/android-rc-pipeline.v1.json",
    root / "data/content/final-promo-media.v1.json",
    root / "data/art/release_candidate_prompt_pack.json",
    root / "data/art/android_store_mock_pack.json",
    root / "data/audio/release_candidate_audio.v1.json",
    root / "data/audio/android_rc_validation.v1.json",
    root / "data/ui/release_candidate_panels.v1.json",
    root / "data/reference/reference-data.v22.releasecandidate.json",
    root / "data/content/android-preview-build.v1.json",
    root / "data/content/release-readiness-checklist.v1.json",
    root / "data/content/telemetry-dashboard.v1.json",
    root / "data/content/review-feedback-dashboard.v1.json",
    root / "data/content/final-capture-pack.v1.json",
    root / "data/art/android_preview_prompt_pack.json",
    root / "data/audio/android_preview_audio_review.v1.json",
    root / "data/ui/telemetry_review_panels.v1.json",
    root / "data/reference/reference-data.v23.androidpreview.json",
    root / "data/content/real-android-build.v1.json",
    root / "data/content/bugfix-freeze.v1.json",
    root / "data/content/operator-dispatcher-showcase.v1.json",
    root / "data/content/final-polish-pack.v2.json",
    root / "data/content/release-feedback-loop.v2.json",
    root / "data/art/real_android_build_prompt_pack.json",
    root / "data/art/operator_dispatcher_showcase_prompt_pack.json",
    root / "data/audio/real_android_build_audio_lock.v1.json",
    root / "data/audio/operator_dispatcher_showcase_audio.v1.json",
    root / "data/ui/real_android_build_panels.v1.json",
    root / "data/reference/reference-data.v26.realandroid.json",
]
errors = []
for f in files:
    if not f.exists():
        errors.append(f"Missing file: {f}")
        continue
    try:
        data = json.loads(f.read_text(encoding='utf-8'))
    except Exception as ex:
        errors.append(f"Invalid JSON {f}: {ex}")
        continue
    print(f"OK {f.name}")
    if f.name in {"reference-data.extended.json", "reference-data.v7.routing.json", "reference-data.v8.rounds.json", "reference-data.v9.menuartaudio.json", "reference-data.v10.homeflow.json", "reference-data.v11.campaignentry.json", "reference-data.v12.runtimebootstrap.json", "reference-data.v14.fullmission.json", "reference-data.v15.playableflow.json", "reference-data.v16.liveroute.json", "reference-data.v17.quasiprod.json", "reference-data.v22.releasecandidate.json", "reference-data.v23.androidpreview.json", "reference-data.v26.realandroid.json"}:
        ids = []
        for group in data.get("groups", []):
            for entry in group.get("entries", []):
                ids.append(entry.get("id"))
        dupes = sorted({x for x in ids if x and ids.count(x) > 1})
        if dupes:
            errors.append(f"Duplicate IDs in {f.name}: {dupes}")
if errors:
    print("\n".join(errors))
    sys.exit(1)
print("[content-verify] success")
PY2
