#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
require_file () { if [ ! -f "$1" ]; then echo "Missing required file: $1" >&2; exit 1; fi; }
require_file "$ROOT/docs/implementation/36_V20_SHOWCASE_DEMO_PACKAGE_SCOPE.md"
require_file "$ROOT/docs/ui/56_FIRST_TIME_USER_EXPERIENCE_AND_ONBOARDING.md"
require_file "$ROOT/docs/ui/57_SHOWCASE_DEMO_FLOW_AND_CAPTURE_PLAN.md"
require_file "$ROOT/docs/ui/58_PLAYER_FACING_POLISH_PACK.md"
require_file "$ROOT/docs/art/57_SHOWCASE_MISSION_SCENES_AND_OBJECTS_V7.md"
require_file "$ROOT/docs/audio/40_ONBOARDING_SHOWCASE_AUDIO.md"
require_file "$ROOT/docs/gameplay/51_SHOWCASE_MISSION_SCRIPT_AND_ONBOARDING.md"
require_file "$ROOT/docs/network/19_SHOWCASE_DEMO_SESSION_AND_BOT_FILL_SYNC.md"
require_file "$ROOT/docs/backend/17_SHOWCASE_DEMO_PACKAGE_API.md"
require_file "$ROOT/docs/data/38_SHOWCASE_ONBOARDING_DICTIONARIES.md"
require_file "$ROOT/data/content/showcase-mission.v1.json"
require_file "$ROOT/data/content/onboarding-flow.v1.json"
require_file "$ROOT/data/content/hint-system.v1.json"
require_file "$ROOT/data/content/demo-presentation-flow.v1.json"
require_file "$ROOT/data/content/player-facing-polish.v1.json"
require_file "$ROOT/data/reference/reference-data.v20.showcase.json"
require_file "$ROOT/src/Alarm112.Contracts/ShowcaseMissionDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/OnboardingFlowDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/PlayerFacingPolishDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/DemoCapturePlanDto.cs"
require_file "$ROOT/src/Alarm112.Application/Interfaces/IShowcaseDemoService.cs"
require_file "$ROOT/src/Alarm112.Application/Services/ShowcaseDemoService.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Menu/OnboardingFlowController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/Hints/ContextHintController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/ShowcaseMissionFlowController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Menu/DemoPresentationFlowController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Art/PlayerFacingPolishController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Audio/OnboardingShowcaseAudioController.cs"
grep -q '/api/showcase-mission/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/onboarding-flow/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/hint-system/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/demo-presentation-flow/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/player-facing-polish/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/demo-capture-plan/demo' "$ROOT/src/Alarm112.Api/Program.cs"
echo "V20 smoke passed."
