#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
require_file () { if [ ! -f "$1" ]; then echo "Missing required file: $1" >&2; exit 1; fi; }
require_file "$ROOT/docs/implementation/28_V16_LIVE_ROUTE_OBJECTIVE_TIMER_SCOPE.md"
require_file "$ROOT/docs/ui/43_LIVE_ROUTE_RENDERER_AND_ROUND_TIMER.md"
require_file "$ROOT/docs/art/45_LIVE_ROUTE_RENDERER_MARKERS_TRAILS_V3.md"
require_file "$ROOT/docs/audio/28_LIVE_ROUTE_TIMER_CHAIN_ALERT_AUDIO.md"
require_file "$ROOT/docs/gameplay/39_LIVE_ROUTE_RENDERER_AND_ROUND_TIMER_RULES.md"
require_file "$ROOT/docs/backend/13_LIVE_ROUTE_TIMER_CHAIN_API.md"
require_file "$ROOT/data/content/live-route-runtime.v1.json"
require_file "$ROOT/data/content/round-timer.v1.json"
require_file "$ROOT/data/content/chain-escalation-runtime.v1.json"
require_file "$ROOT/data/content/demo-mission-polish.v1.json"
require_file "$ROOT/data/reference/reference-data.v16.liveroute.json"
require_file "$ROOT/src/Alarm112.Contracts/LiveRouteRuntimeDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/LiveRouteSegmentStateDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/RoundTimerDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/ChainEscalationStateDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/DemoMissionPolishDto.cs"
require_file "$ROOT/src/Alarm112.Application/Interfaces/IRuntimePolishService.cs"
require_file "$ROOT/src/Alarm112.Application/Services/RuntimePolishService.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Map/LiveRouteRendererController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/RoundTimerController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/ChainEscalationController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/ObjectiveTransitionHudController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Art/DemoMissionPolishController.cs"
grep -q '/api/live-route-runtime/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/round-timer/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/chain-escalation-runtime/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/demo-mission-polish/demo' "$ROOT/src/Alarm112.Api/Program.cs"
echo "V16 smoke passed."
