#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
require_file () { if [ ! -f "$1" ]; then echo "Missing required file: $1" >&2; exit 1; fi; }
require_file "$ROOT/docs/implementation/34_V19_SCOREBOARD_REWARDS_RETRYPREP_SCOPE.md"
require_file "$ROOT/docs/ui/53_RUNTIME_SCOREBOARD_AND_REWARD_REVEAL.md"
require_file "$ROOT/docs/ui/54_RETRY_PREPARATION_AND_NEXT_MISSION_HANDOFF.md"
require_file "$ROOT/docs/ui/55_NEAR_FINAL_VERTICAL_SLICE_FLOW.md"
require_file "$ROOT/docs/art/54_NEAR_FINAL_2D_OBJECTS_SCENES_V6.md"
require_file "$ROOT/docs/audio/37_RUNTIME_SCOREBOARD_REWARD_AUDIO.md"
require_file "$ROOT/docs/gameplay/48_RUNTIME_SCOREBOARD_AND_REWARD_REVEAL_RULES.md"
require_file "$ROOT/docs/network/18_SCOREBOARD_REWARD_RETRY_SYNC.md"
require_file "$ROOT/docs/backend/16_SCOREBOARD_REWARD_RETRYPREP_API.md"
require_file "$ROOT/docs/data/36_SCOREBOARD_REWARD_RETRY_DICTIONARIES.md"
require_file "$ROOT/data/content/runtime-scoreboard.v1.json"
require_file "$ROOT/data/content/reward-reveal-states.v1.json"
require_file "$ROOT/data/content/retry-preparation.v1.json"
require_file "$ROOT/data/content/next-mission-handoff.v1.json"
require_file "$ROOT/data/reference/reference-data.v19.scoreboard.json"
require_file "$ROOT/src/Alarm112.Contracts/RuntimeScoreboardDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/RewardRevealStateDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/RetryPreparationDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/NextMissionHandoffDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/NearFinalSliceFlowDto.cs"
require_file "$ROOT/src/Alarm112.Application/Interfaces/INearFinalSliceService.cs"
require_file "$ROOT/src/Alarm112.Application/Services/NearFinalSliceService.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/Reports/RuntimeScoreboardController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/Reports/RewardRevealStateController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/RetryPreparationController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Menu/NextMissionHandoffController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/NearFinalSliceFlowController.cs"
grep -q '/api/runtime-scoreboard/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/reward-reveal/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/retry-preparation/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/next-mission-handoff/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/near-final-slice-flow/demo' "$ROOT/src/Alarm112.Api/Program.cs"
echo "V19 smoke passed."
