#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
require_file () { if [ ! -f "$1" ]; then echo "Missing required file: $1" >&2; exit 1; fi; }
require_file "$ROOT/docs/implementation/32_V18_RUNTIME_UI_RECOVERY_SCOPE.md"
require_file "$ROOT/docs/ui/49_RUNTIME_MISSION_HUD_V2.md"
require_file "$ROOT/docs/ui/50_RECOVERY_CARDS_IN_HUD.md"
require_file "$ROOT/docs/ui/51_FAIL_RETRY_NEXT_FLOW.md"
require_file "$ROOT/docs/art/51_PREMIUM_2D_RUNTIME_OBJECTS_SCENES_V5.md"
require_file "$ROOT/docs/audio/34_RUNTIME_HUD_RECOVERY_RETRY_AUDIO.md"
require_file "$ROOT/docs/gameplay/45_RUNTIME_UI_USECASES_AND_CARD_TRIGGERS.md"
require_file "$ROOT/docs/network/17_RUNTIME_RECOVERY_CARD_HUD_SYNC.md"
require_file "$ROOT/docs/backend/15_RUNTIME_UI_RECOVERY_RETRY_API.md"
require_file "$ROOT/docs/data/34_RUNTIME_UI_RETRY_DICTIONARIES.md"
require_file "$ROOT/data/content/runtime-hud.v2.json"
require_file "$ROOT/data/content/recovery-card-usecases.v2.json"
require_file "$ROOT/data/content/fail-retry-next-flow.v1.json"
require_file "$ROOT/data/content/premium-slice-pack.v1.json"
require_file "$ROOT/data/reference/reference-data.v18.runtimeui.json"
require_file "$ROOT/src/Alarm112.Contracts/RuntimeHudDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/RecoveryHudTriggerDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/FailRetryNextFlowDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/MissionSlicePolishDto.cs"
require_file "$ROOT/src/Alarm112.Application/Interfaces/IRuntimeUiFlowService.cs"
require_file "$ROOT/src/Alarm112.Application/Services/RuntimeUiFlowService.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/RuntimeHudV2Controller.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/RecoveryCardHudController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/Reports/FailRetryNextFlowController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Art/MissionSlicePolishController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Audio/RuntimeRecoveryRetryAudioController.cs"
grep -q '/api/runtime-hud/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/recovery-hud-triggers/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/fail-retry-next/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/mission-slice-polish/demo' "$ROOT/src/Alarm112.Api/Program.cs"
echo "V18 smoke passed."
