#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
require_file () { if [ ! -f "$1" ]; then echo "Missing required file: $1" >&2; exit 1; fi; }
require_file "$ROOT/docs/implementation/30_V17_QUASI_PRODUCTION_DEMO_SCOPE.md"
require_file "$ROOT/docs/ui/46_VISUAL_RUNTIME_ROUTE_LAYER_AND_RECOVERY_CARDS.md"
require_file "$ROOT/docs/art/48_VISUAL_RUNTIME_ROUTE_LAYER_V4.md"
require_file "$ROOT/docs/audio/31_RECOVERY_FAILSTATE_REPORT_ROOM_AUDIO.md"
require_file "$ROOT/docs/gameplay/42_RECOVERY_DECISION_CARDS_AND_FAIL_BRANCH_RULES.md"
require_file "$ROOT/docs/backend/14_RECOVERY_FAIL_REPORT_API.md"
require_file "$ROOT/data/content/visual-runtime-route-layer.v1.json"
require_file "$ROOT/data/content/recovery-decision-cards.v1.json"
require_file "$ROOT/data/content/mission-fail-branches.v1.json"
require_file "$ROOT/data/content/report-room-polish.v1.json"
require_file "$ROOT/data/content/quasi-production-demo-flow.v1.json"
require_file "$ROOT/data/reference/reference-data.v17.quasiprod.json"
require_file "$ROOT/src/Alarm112.Contracts/VisualRuntimeRouteLayerDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/RecoveryDecisionCardDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/MissionFailBranchDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/ReportRoomPolishDto.cs"
require_file "$ROOT/src/Alarm112.Contracts/QuasiProductionDemoFlowDto.cs"
require_file "$ROOT/src/Alarm112.Application/Interfaces/IQuasiProductionDemoService.cs"
require_file "$ROOT/src/Alarm112.Application/Services/QuasiProductionDemoService.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Map/VisualRuntimeRouteLayerController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/RecoveryDecisionCardsController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/MissionFailBranchController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/UI/Reports/ReportRoomPolishController.cs"
require_file "$ROOT/client-unity/Assets/Scripts/Runtime/Session/QuasiProductionDemoFlowController.cs"
grep -q '/api/visual-runtime-route-layer/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/recovery-decision-cards/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/mission-fail-branches/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/report-room-polish/demo' "$ROOT/src/Alarm112.Api/Program.cs"
grep -q '/api/quasi-production-demo-flow/demo' "$ROOT/src/Alarm112.Api/Program.cs"
echo "V17 smoke passed."
